# -*- coding: utf-8 -*-
# Auto-generated by sql2pyapi from array_types_function.sql
#
# IMPORTANT: This code expects the database connection to use the default
# psycopg tuple row factory. It will raise errors if used with
# dictionary-based row factories (like DictRow).

from typing import List, Optional, Tuple, Dict, Any
from psycopg import AsyncConnection


async def get_item_ids(conn: AsyncConnection) -> Optional[List[int]]:
    """Returns an array of integers"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_item_ids()", [])
        row = await cur.fetchone()
        if row is None:
            return None
        # Expecting a tuple even for scalar returns, access first element.
        return row[0]

async def process_tags(conn: AsyncConnection, tags: List[str]) -> Optional[List[str]]:
    """Takes and returns an array of text"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM process_tags(%s)", [tags])
        row = await cur.fetchone()
        if row is None:
            return None
        # Expecting a tuple even for scalar returns, access first element.
        return row[0]
