# -*- coding: utf-8 -*-
# Auto-generated by sql2pyapi from example_schema1.sql
#
# IMPORTANT: This code expects the database connection to use the default
# psycopg tuple row factory. It will raise errors if used with
# dictionary-based row factories (like DictRow).

from typing import List, Optional, Tuple, Dict, Any
from psycopg import AsyncConnection


async def trigger_set_timestamp(conn: AsyncConnection) -> Optional[Any]:
    """Trigger function to set updated_at timestamp"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM trigger_set_timestamp()", [])
        row = await cur.fetchone()
        if row is None:
            return None
        # Expecting a tuple even for scalar returns, access first element.
        return row[0]
