# -*- coding: utf-8 -*-
# Auto-generated by sql2pyapi from multi_params_function.sql
#
# IMPORTANT: This code expects the database connection to use the default
# psycopg tuple row factory. It will raise errors if used with
# dictionary-based row factories (like DictRow).

from typing import List, Optional, Tuple, Dict, Any
from uuid import UUID
from decimal import Decimal
from psycopg import AsyncConnection


async def add_item(conn: AsyncConnection, name: str, category_id: int, is_available: bool, price: Decimal, attributes: Dict[str, Any]) -> Optional[UUID]:
    """Adds an item with various attributes"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM add_item(%s, %s, %s, %s, %s)", [name, category_id, is_available, price, attributes])
        row = await cur.fetchone()
        if row is None:
            return None
        # Expecting a tuple even for scalar returns, access first element.
        return row[0]
