# Generated by sql-to-python-api from multi_params_function.sql
# DO NOT EDIT MANUALLY
from decimal import Decimal
from psycopg import AsyncConnection
from typing import Any, Dict, Optional
from uuid import UUID



async def add_item(conn: AsyncConnection, name: str, category_id: int, is_available: bool, price: Decimal, attributes: Dict[str, Any]) -> Optional[UUID]:
    """Adds an item with various attributes"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM add_item(%s, %s, %s, %s, %s)", [name, category_id, is_available, price, attributes])
        row = await cur.fetchone()
        if row is None:
            return None
        # Return first element for scalar
        return row[0]
