# Generated by sql2pyapi from no_params_function.sql
# DO NOT EDIT MANUALLY
from datetime import datetime
from psycopg import AsyncConnection
from typing import Optional

async def get_current_db_time(conn: AsyncConnection) -> Optional[datetime]:
    """Returns the current database time"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_current_db_time()", [])
        row = await cur.fetchone()
        if row is None:
            return None
        if isinstance(row, dict):
            # Assumes the key is the function name for dict rows
            return row['get_current_db_time']
        else:
            # Fallback for tuple-like rows (index 0)
            return row[0]
