# Generated by sql-to-python-api from no_params_function.sql
# DO NOT EDIT MANUALLY
from datetime import datetime
from psycopg import AsyncConnection
from typing import Optional


async def get_current_db_time(conn: AsyncConnection) -> Optional[datetime]:
    """Returns the current database time"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_current_db_time()", [])
        row = await cur.fetchone()
        if row is None:
            return None
        # Return first element for scalar
        return row[0]
