# Generated by sql-to-python-api from optional_params_function.sql
# DO NOT EDIT MANUALLY
from psycopg import AsyncConnection
from typing import List, Optional


# TODO: Define dataclass for table 'items'
# @dataclass
# class Item:
#     pass


async def search_items(
    conn: AsyncConnection,
    query: str,
    limit: Optional[int] = None,
    include_unavailable: Optional[bool] = None,
) -> List[Item]:
    """Search for items with optional filters"""
    async with conn.cursor() as cur:
        await cur.execute(
            "SELECT * FROM search_items(%s, %s, %s)",
            [query, limit, include_unavailable],
        )
        rows = await cur.fetchall()
        # Ensure dataclass 'Item' is defined above.
        return [Item(*row) for row in rows] if rows else []
