# -*- coding: utf-8 -*-

# Auto-generated by sql2pyapi from param_comments_function.sql

from typing import List, Optional, Tuple, Dict, Any
from uuid import UUID
from psycopg import AsyncConnection

async def function_with_param_comments(conn: AsyncConnection, id: UUID, name: str, active: bool, age: Optional[int] = None) -> None:
    """Function with comments in parameters"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM function_with_param_comments(%s, %s, %s, %s)", [id, name, active, age])
        return None
