# -*- coding: utf-8 -*-
# Auto-generated by sql2pyapi from returns_table_comments_function.sql
#
# IMPORTANT: This code expects the database connection to use the default
# psycopg tuple row factory. It will raise errors if used with
# dictionary-based row factories (like DictRow).

from dataclasses import dataclass
from psycopg import AsyncConnection
from typing import List, Optional, Tuple, Dict, Any
from typing import TypeVar, Sequence
from uuid import UUID

@dataclass
class FunctionWithReturnsTableCommentsResult:
    col_id: Optional[UUID]
    col_value: Optional[str]
    col_status: Optional[bool]

async def function_with_returns_table_comments(conn: AsyncConnection, filter: str) -> List[FunctionWithReturnsTableCommentsResult]:
    """Call PostgreSQL function function_with_returns_table_comments()."""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM function_with_returns_table_comments(%s)", [filter])
        rows = await cur.fetchall()
        # Ensure dataclass 'FunctionWithReturnsTableCommentsResult' is defined above.
        if not rows:
            return []
        try:
            return [FunctionWithReturnsTableCommentsResult(*r) for r in rows]
        except TypeError as e:
            # Tuple unpacking failed. This often happens if the DB connection
            # is configured with a dict-like row factory (e.g., DictRow).
            # This generated code expects the default tuple row factory.
            raise TypeError(
                f"Failed to map SETOF results to dataclass list for FunctionWithReturnsTableCommentsResult. "
                f"Check DB connection: Default tuple row_factory expected. Error: {e}"
            )


# ===== SECTION: RESULT HELPERS =====
# REMOVED redundant import line

T = TypeVar('T')

def get_optional(result: Optional[List[T]] | Optional[T]) -> Optional[T]:
    """\
    Safely retrieves an optional single result.

    Handles cases where the input is:
    - None
    - An empty list
    - A list with one item
    - A single item (non-list, non-None)

    Returns the item if exactly one is found, otherwise None.
    """
    if result is None:
        return None
    # Check if it's a list/tuple but not string/bytes
    if isinstance(result, Sequence) and not isinstance(result, (str, bytes)):
        if len(result) == 1:
            return result[0]
        else: # Empty list or list with more than one item
            return None
    else: # It's already a single item
        return result

def get_required(result: Optional[List[T]] | Optional[T]) -> T:
    """\
    Retrieves a required single result, raising an error if none or multiple are found.

    Handles cases where the input is:
    - None
    - An empty list
    - A list with one item
    - A single item (non-list, non-None)

    Returns the item if exactly one is found.
    Raises ValueError otherwise.
    """
    item = get_optional(result)
    if item is None:
         # Improved error message
         input_repr = repr(result)
         if len(input_repr) > 80: # Truncate long inputs
             input_repr = input_repr[:77] + '...'
         raise ValueError(f"Expected exactly one result, but got none or multiple. Input was: {input_repr}")
    return item

