# -*- coding: utf-8 -*-

# Auto-generated by sql2pyapi from returns_table_function.sql

from typing import List, Optional, Tuple, Dict, Any
from uuid import UUID
from psycopg import AsyncConnection
from dataclasses import dataclass

@dataclass
class GetUserBasicInfoResult:
    user_id: Optional[UUID]
    first_name: Optional[str]
    is_active: Optional[bool]

async def get_user_basic_info(conn: AsyncConnection, user_id: UUID) -> Optional[GetUserBasicInfoResult]:
    """Returns a user's basic info as a table"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_user_basic_info(%s)", [user_id])
        row = await cur.fetchone()
        if row is None:
            return None
        # Ensure dataclass 'GetUserBasicInfoResult' is defined above.
        colnames = [desc[0] for desc in cur.description]
        row_dict = dict(zip(colnames, row)) if not isinstance(row, dict) else row
        return GetUserBasicInfoResult(**row_dict)
