# Generated by sql2py from returns_table_function.sql
# DO NOT EDIT MANUALLY
from dataclasses import dataclass
from psycopg import AsyncConnection
from typing import Optional
from uuid import UUID

@dataclass
class UserBasicInfo:
    user_id: UUID
    first_name: str
    is_active: bool

async def get_user_basic_info(conn: AsyncConnection, user_id: UUID) -> Optional[UserBasicInfo]:
    """Returns a user's basic info as a table"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_user_basic_info(%s)", [user_id])
        row = await cur.fetchone()
        if row is None:
            return None
        # Ensure dataclass 'UserBasicInfo' is defined above.
        return UserBasicInfo(*row)
