# Generated by sql-to-python-api from scalar_function.sql
# DO NOT EDIT MANUALLY
from psycopg import AsyncConnection
from typing import Optional


async def get_item_count(conn: AsyncConnection) -> Optional[int]:
    """Returns a simple count"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_item_count()", [])
        row = await cur.fetchone()
        if row is None:
            return None
        # Return first element for scalar
        return row[0]


async def get_item_name(conn: AsyncConnection, id: int) -> Optional[str]:
    """Returns text, potentially null"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_item_name(%s)", [id])
        row = await cur.fetchone()
        if row is None:
            return None
        # Return first element for scalar
        return row[0]
