# -*- coding: utf-8 -*-
# Auto-generated by sql2pyapi from scalar_function.sql
#
# IMPORTANT: This code expects the database connection to use the default
# psycopg tuple row factory. It will raise errors if used with
# dictionary-based row factories (like DictRow).

from typing import List, Optional, Tuple, Dict, Any
from psycopg import AsyncConnection


async def get_item_count(conn: AsyncConnection) -> Optional[int]:
    """Returns a simple count"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_item_count()", [])
        row = await cur.fetchone()
        if row is None:
            return None
        # Expecting a tuple even for scalar returns, access first element.
        return row[0]

async def get_item_name(conn: AsyncConnection, id: int) -> Optional[str]:
    """Returns text, potentially null"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_item_name(%s)", [id])
        row = await cur.fetchone()
        if row is None:
            return None
        # Expecting a tuple even for scalar returns, access first element.
        return row[0]
