# Generated by sql-to-python-api from setof_missing_table_function.sql
# DO NOT EDIT MANUALLY
from dataclasses import dataclass
from psycopg import AsyncConnection
from typing import Any, List


# TODO: Define dataclass for table 'some_undefined_table'
# @dataclass
# class SomeUndefinedTable:
#     pass



async def get_undefined_table_data(conn: AsyncConnection) -> List[SomeUndefinedTable]:
    """The schema for 'some_undefined_table' is intentionally missing."""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_undefined_table_data()", [])
        rows = await cur.fetchall()
        # Ensure dataclass 'SomeUndefinedTable' is defined above.
        return [SomeUndefinedTable(*row) for row in rows] if rows else []
