# Generated by sql2py from setof_missing_table_function.sql
# DO NOT EDIT MANUALLY
from dataclasses import dataclass
from psycopg import AsyncConnection
from typing import Any, List

# TODO: Define dataclass for table 'some_undefined_table'
# @dataclass
# class SomeUndefinedTable:
#     pass

async def get_undefined_table_data(conn: AsyncConnection) -> List[SomeUndefinedTable]:
    """Returns a setof some_undefined_table records
    The schema for 'some_undefined_table' is intentionally missing.
    """
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_undefined_table_data()", [])
        rows = await cur.fetchall()
        # Ensure dataclass 'SomeUndefinedTable' is defined above.
        if not rows:
            return []
        colnames = [desc[0] for desc in cur.description]
        processed_rows = [
            dict(zip(colnames, r)) if not isinstance(r, dict) else r
            for r in rows
        ]
        return [SomeUndefinedTable(**row_dict) for row_dict in processed_rows]
