# -*- coding: utf-8 -*-

# Auto-generated by sql2pyapi from setof_scalar_function.sql

from typing import List, Optional, Tuple, Dict, Any
from psycopg import AsyncConnection

async def get_item_ids_by_category(conn: AsyncConnection, category_name: str) -> List[int]:
    """Returns a list of item IDs for a given category"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_item_ids_by_category(%s)", [category_name])
        rows = await cur.fetchall()
        # Assuming SETOF returns list of single-element tuples for scalars
        return [row[0] for row in rows if row]
