# -*- coding: utf-8 -*-
# Auto-generated by sql2pyapi from single_line_enum.sql
#
# IMPORTANT: This code expects the database connection to use the default
# psycopg tuple row factory. It will raise errors if used with
# dictionary-based row factories (like DictRow).

from dataclasses import dataclass
from enum import Enum
from psycopg import AsyncConnection
from typing import List, Optional, Tuple, Dict, Any
from typing import TypeVar, Sequence

class CompanyRole(Enum):
    OWNER = 'owner'
    ADMIN = 'admin'
    MEMBER = 'member'


@dataclass
class GetUserRolesResult:
    user_id: Optional[int]
    role: Optional[CompanyRole]

async def get_role_description(conn: AsyncConnection, role: CompanyRole) -> Optional[str]:
    """Function that uses the enum type as a parameter"""
    # Extract .value from enum parameters
        role_value = role.value if role is not None else None
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_role_description(%s)", [role_value])
        row = await cur.fetchone()
        if row is None:
            return None
        return row[0]

async def get_default_role(conn: AsyncConnection) -> CompanyRole:
    """Function that returns the enum type"""
        async with conn.cursor() as cur:
            await cur.execute("SELECT * FROM get_default_role()", [])
            row = await cur.fetchone()
            if row is None:
                return None
            return CompanyRole(row[0])

async def get_user_roles(conn: AsyncConnection) -> List[GetUserRolesResult]:
    """Function that returns a table with an enum column"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM get_user_roles()", [])
        rows = await cur.fetchall()
        # Ensure dataclass 'GetUserRolesResult' is defined above.
        if not rows:
            return []
        # Inner helper function for efficient conversion
        def create_getuserrolesresult(row):
            return GetUserRolesResult(
                    user_id=row[0],
                    role=CompanyRole(row[1]) if row[1] is not None else None
                )

        try:
            return [create_getuserrolesresult(row) for row in rows]
        except TypeError as e:
            # Tuple unpacking failed. This often happens if the DB connection
            # is configured with a dict-like row factory (e.g., DictRow).
            # This generated code expects the default tuple row factory.
            raise TypeError(
                f"Failed to map SETOF results to dataclass list for GetUserRolesResult. "
                f"Check DB connection: Default tuple row_factory expected. Error: {e}"
            )


# ===== SECTION: RESULT HELPERS =====
# REMOVED redundant import line

T = TypeVar('T')

def get_optional(result: Optional[List[T]] | Optional[T]) -> Optional[T]:
    """\
    Safely retrieves an optional single result.

    Handles cases where the input is:
    - None
    - An empty list
    - A list with one item
    - A single item (non-list, non-None)

    Returns the item if exactly one is found, otherwise None.
    """
    if result is None:
        return None
    # Check if it's a list/tuple but not string/bytes
    if isinstance(result, Sequence) and not isinstance(result, (str, bytes)):
        if len(result) == 1:
            return result[0]
        else: # Empty list or list with more than one item
            return None
    else: # It's already a single item
        return result

def get_required(result: Optional[List[T]] | Optional[T]) -> T:
    """\
    Retrieves a required single result, raising an error if none or multiple are found.

    Handles cases where the input is:
    - None
    - An empty list
    - A list with one item
    - A single item (non-list, non-None)

    Returns the item if exactly one is found.
    Raises ValueError otherwise.
    """
    item = get_optional(result)
    if item is None:
         # Improved error message
         input_repr = repr(result)
         if len(input_repr) > 80: # Truncate long inputs
             input_repr = input_repr[:77] + '...'
         raise ValueError(f"Expected exactly one result, but got none or multiple. Input was: {input_repr}")
    return item

