# Generated by sql2py from void_function.sql
# DO NOT EDIT MANUALLY
from psycopg import AsyncConnection

async def do_something(conn: AsyncConnection, item_id: int) -> None:
    """A function that does something but returns nothing"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM do_something(%s)", [item_id])
        return None
