# -*- coding: utf-8 -*-
# Auto-generated by sql2pyapi from void_function.sql
#
# IMPORTANT: This code expects the database connection to use the default
# psycopg tuple row factory. It will raise errors if used with
# dictionary-based row factories (like DictRow).

from psycopg import AsyncConnection


async def do_something(conn: AsyncConnection, item_id: int) -> None:
    """A function that does something but returns nothing"""
    async with conn.cursor() as cur:
        await cur.execute("SELECT * FROM do_something(%s)", [item_id])
        return None
